`timescale 1ns/1ps

import traffic_replay_pkg::*;

module traffic_replay_top_stub #(
  parameter int AXIL_ADDR_W = 16,
  parameter int AXI_ADDR_W_P = AXI_ADDR_W,
  parameter int AXI_ID_W_P   = AXI_ID_W
) (
  input  logic                     clk,
  input  logic                     rstn,
  input  logic                     link_up,

  input  logic [AXIL_ADDR_W-1:0]   s_axil_awaddr,
  input  logic                     s_axil_awvalid,
  output logic                     s_axil_awready,
  input  logic [31:0]              s_axil_wdata,
  input  logic [3:0]               s_axil_wstrb,
  input  logic                     s_axil_wvalid,
  output logic                     s_axil_wready,
  output logic [1:0]               s_axil_bresp,
  output logic                     s_axil_bvalid,
  input  logic                     s_axil_bready,
  input  logic [AXIL_ADDR_W-1:0]   s_axil_araddr,
  input  logic                     s_axil_arvalid,
  output logic                     s_axil_arready,
  output logic [31:0]              s_axil_rdata,
  output logic [1:0]               s_axil_rresp,
  output logic                     s_axil_rvalid,
  input  logic                     s_axil_rready,

  input  logic [AXIS_DATA_W-1:0]   s_host_axis_tdata,
  input  logic [AXIS_KEEP_W-1:0]   s_host_axis_tkeep,
  input  logic                     s_host_axis_tvalid,
  output logic                     s_host_axis_tready,
  input  logic                     s_host_axis_tlast,

  output logic [AXI_ID_W_P-1:0]    m_axi_arid,
  output logic [AXI_ADDR_W_P-1:0]  m_axi_araddr,
  output logic [7:0]               m_axi_arlen,
  output logic [2:0]               m_axi_arsize,
  output logic [1:0]               m_axi_arburst,
  output logic                     m_axi_arvalid,
  input  logic                     m_axi_arready,
  input  logic [AXI_ID_W_P-1:0]    m_axi_rid,
  input  logic [AXIS_DATA_W-1:0]   m_axi_rdata,
  input  logic [1:0]               m_axi_rresp,
  input  logic                     m_axi_rlast,
  input  logic                     m_axi_rvalid,
  output logic                     m_axi_rready,

  output logic [AXIS_DATA_W-1:0]   m_tx_axis_tdata,
  output logic [AXIS_KEEP_W-1:0]   m_tx_axis_tkeep,
  output logic                     m_tx_axis_tvalid,
  input  logic                     m_tx_axis_tready,
  output logic                     m_tx_axis_tlast,
  output logic                     m_tx_axis_tuser
);
  trace_replay_core #(
    .AXIL_ADDR_W(AXIL_ADDR_W),
    .AXI_ADDR_W_P(AXI_ADDR_W_P),
    .AXI_ID_W_P(AXI_ID_W_P)
  ) core_i (
    .clk(clk),
    .rstn(rstn),
    .link_up(link_up),
    .s_axil_awaddr(s_axil_awaddr),
    .s_axil_awvalid(s_axil_awvalid),
    .s_axil_awready(s_axil_awready),
    .s_axil_wdata(s_axil_wdata),
    .s_axil_wstrb(s_axil_wstrb),
    .s_axil_wvalid(s_axil_wvalid),
    .s_axil_wready(s_axil_wready),
    .s_axil_bresp(s_axil_bresp),
    .s_axil_bvalid(s_axil_bvalid),
    .s_axil_bready(s_axil_bready),
    .s_axil_araddr(s_axil_araddr),
    .s_axil_arvalid(s_axil_arvalid),
    .s_axil_arready(s_axil_arready),
    .s_axil_rdata(s_axil_rdata),
    .s_axil_rresp(s_axil_rresp),
    .s_axil_rvalid(s_axil_rvalid),
    .s_axil_rready(s_axil_rready),
    .s_host_axis_tdata(s_host_axis_tdata),
    .s_host_axis_tkeep(s_host_axis_tkeep),
    .s_host_axis_tvalid(s_host_axis_tvalid),
    .s_host_axis_tready(s_host_axis_tready),
    .s_host_axis_tlast(s_host_axis_tlast),
    .m_axi_arid(m_axi_arid),
    .m_axi_araddr(m_axi_araddr),
    .m_axi_arlen(m_axi_arlen),
    .m_axi_arsize(m_axi_arsize),
    .m_axi_arburst(m_axi_arburst),
    .m_axi_arvalid(m_axi_arvalid),
    .m_axi_arready(m_axi_arready),
    .m_axi_rid(m_axi_rid),
    .m_axi_rdata(m_axi_rdata),
    .m_axi_rresp(m_axi_rresp),
    .m_axi_rlast(m_axi_rlast),
    .m_axi_rvalid(m_axi_rvalid),
    .m_axi_rready(m_axi_rready),
    .m_tx_axis_tdata(m_tx_axis_tdata),
    .m_tx_axis_tkeep(m_tx_axis_tkeep),
    .m_tx_axis_tvalid(m_tx_axis_tvalid),
    .m_tx_axis_tready(m_tx_axis_tready),
    .m_tx_axis_tlast(m_tx_axis_tlast),
    .m_tx_axis_tuser(m_tx_axis_tuser)
  );
endmodule
